
services:
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    container_name: server

  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    container_name: client
    depends_on:
      - server