FROM debian:stable-slim
RUN apt-get update && apt-get install -y build-essential cmake
WORKDIR /app
COPY . .
RUN cmake -S. -Bbuild && cmake --build build --target udp_server
CMD ["./build/server/udp_server"]